print(1)
print(2)
print(3)
print(4)
print(5)
print(6)
print(7)
print(8)
print(9)
print(10)
  
					# The same task done like this 
# Prompt the user to enter the start number and convert it to an integer
a = int(input("Enter the Start Number: "))

# Prompt the user to enter the end number and convert it to an integer
b = int(input("Enter the End Number: "))

# Loop through the range from the start number to the end number (inclusive)
for i in range(a, b + 1): 
    # Print each number in the range
    print(i)


#    Read More
"""
                    How the code works:
    1.  Input: The program prompts the user to enter two numbers:
	•	The start number (a).
	•	The end number (b).
	2.	Conversion: The input values are read as strings and then converted to integers using the int() function.
	3.	For Loop:
	•	The for loop iterates over a range of numbers starting from a to b inclusive.
	•	The range(a, b + 1) function generates a sequence of numbers starting from a and ending at b (inclusive of b).
	4.	Printing:
	•	Inside the loop, each number in the range is printed.
	•	The loop variable i takes on each value in the sequence generated by range(a, b + 1).

Example:

If the user inputs 3 for the start number and 7 for the end number:

	•	The range(3, 8) generates the sequence: 3, 4, 5, 6, 7.
	•	The loop iterates over this sequence, and in each iteration, it prints the current value of i.

The output will be:
3
4
5
6
7
"""